import fs from 'node:fs/promises';
import path from 'node:path';

const ORIGIN = 'https://chatcut.io';
const OUT = path.resolve('chatcut-playable');

const PATCH_CSS = String.raw`
/* ChatCut playable patch: preserve production layout, add only causal local states. */
.cc-demo-status{margin-top:8px;color:#7b736a;font-size:12px;line-height:1.35}.cc-local-send{display:grid;place-items:center;width:30px;height:30px;padding:0;border:0;border-radius:999px;background:#111;color:#fff;cursor:pointer;box-shadow:0 5px 16px rgba(0,0,0,.12)}.cc-local-send svg{width:15px;height:15px}.cc-local-send:hover{opacity:.88}.cc-local-send:active{transform:scale(.96)}
#best-moments.cc-expert-awaiting .bm-stage *{animation-play-state:paused!important}#best-moments .bm-prompt-card{pointer-events:auto!important}#best-moments .bm-prompt-input{position:relative;padding-right:42px}#best-moments .bm-prompt-input>.cc-local-send{position:absolute;right:7px;top:50%;transform:translateY(-50%);z-index:6}#best-moments .bm-prompt-input>.cc-local-send:active{transform:translateY(-50%) scale(.96)}#best-moments.cc-expert-running .bm-final-video-card{opacity:1}
#motion-graphics.cc-motion-awaiting .agentic-thinking-card{opacity:.28;filter:saturate(.55) blur(.6px);transition:opacity .35s ease,filter .35s ease,transform .35s ease}#motion-graphics.cc-motion-generated .agentic-thinking-card{opacity:1;filter:none;transition:opacity .35s ease,filter .35s ease,transform .35s ease}#motion-graphics.cc-motion-generated .agentic-thinking-card:nth-child(2){transform:translateY(-4px);box-shadow:0 18px 42px rgba(35,28,20,.14)}
#image-to-video .itv-showcase{position:relative}.cc-generate-overlay{position:absolute;inset:0;z-index:15;display:flex;align-items:center;justify-content:center;gap:9px;background:rgba(255,255,255,.78);backdrop-filter:blur(5px);color:#211a13;font-size:13px;font-weight:650}.cc-spinner{width:16px;height:16px;border:2px solid rgba(33,26,19,.18);border-top-color:#211a13;border-radius:50%;animation:cc-spin .7s linear infinite}@keyframes cc-spin{to{transform:rotate(360deg)}}#image-to-video .itv-story.cc-image-loading .itv-showcase-img{filter:saturate(.55)}
#image-to-video .itv-video-showcase{position:relative}#image-to-video .cc-video-reference-overlay{position:absolute;inset:0;z-index:10;width:100%;height:100%;object-fit:cover;background:#f3f0ea}#image-to-video .itv-story-video.cc-video-awaiting .itv-showcase-video,#image-to-video .itv-story-video.cc-video-awaiting .itv-video-poster{opacity:0!important}#image-to-video .itv-story-video.cc-video-generated .itv-showcase-video{opacity:1!important}
#music-generation .cc-music-source-row{display:grid;grid-template-columns:minmax(180px,.7fr) minmax(230px,1.3fr);gap:12px;margin-bottom:12px}#music-generation .cc-music-source-video{position:relative;overflow:hidden;aspect-ratio:16/9;border-radius:12px;background:#171719}#music-generation .cc-music-source-video video{width:100%;height:100%;object-fit:cover;display:block}#music-generation .cc-audio-badge{position:absolute;right:8px;top:8px;padding:5px 8px;border-radius:999px;background:rgba(0,0,0,.62);color:#fff;font-size:10px;font-weight:650}#music-generation .cc-music-prompt-card{position:relative;min-height:100%;padding:14px 50px 30px 14px;border:1px solid #e5e0d8;border-radius:12px;background:#fff;color:#211a13;box-shadow:0 12px 30px rgba(35,28,20,.07)}#music-generation .cc-music-prompt-label{margin-bottom:7px;color:#7b736a;font-size:10px;font-weight:650;text-transform:uppercase;letter-spacing:.08em}#music-generation .cc-music-prompt-text{font-size:13px;line-height:1.45}#music-generation .cc-music-prompt-card>.cc-local-send{position:absolute;right:10px;bottom:10px}#music-generation .cc-music-prompt-card>.cc-demo-status{position:absolute;left:14px;bottom:12px;margin:0;font-size:10px}#music-generation.cc-music-awaiting .tc-music-board{opacity:.34;filter:saturate(.5);transition:opacity .4s ease,filter .4s ease}#music-generation.cc-music-generated .tc-music-board{opacity:1;filter:none;transition:opacity .4s ease,filter .4s ease}
@media(max-width:720px){#music-generation .cc-music-source-row{grid-template-columns:1fr}}@media(prefers-reduced-motion:reduce){.cc-spinner{animation:none!important}#motion-graphics .agentic-thinking-card,#music-generation .tc-music-board{transition:none!important}}
`;

const PATCH_JS = String.raw`
(() => {
const session={expert:'idle',motion:'idle',transcript:'raw',image:'source',video:'reference',music:'silent'};window.__chatcutDemoSession=session;
const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)];
const status=t=>{const e=document.createElement('div');e.className='cc-demo-status';e.textContent=t;return e};
const send=l=>{const b=document.createElement('button');b.type='button';b.className='cc-local-send';b.setAttribute('aria-label',l);b.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m5 12 7-7 7 7M12 19V5" fill="none" stroke="currentColor" stroke-width="2.3" stroke-linecap="round" stroke-linejoin="round"/></svg>';return b};
const loading=(r,t)=>{const e=document.createElement('div');e.className='cc-generate-overlay';e.innerHTML='<span class="cc-spinner"></span><span>'+t+'</span>';r.append(e);return e};
function bindExpert(){const r=q('#best-moments');if(!r||r.dataset.ccBound)return;r.dataset.ccBound='1';r.classList.add('cc-expert-awaiting');const v=q('.bm-final-video',r),p=q('.bm-prompt-input',r);if(!v||!p)return;v.pause();try{v.currentTime=0}catch{};v.addEventListener('play',()=>{if(session.expert==='idle'){v.pause();try{v.currentTime=0}catch{}}});const b=send('Apply editing prompt');p.append(b);p.closest('.bm-prompt-card')?.setAttribute('aria-hidden','false');const s=status('Paused · send the edit instruction');q('.bm-header',r)?.append(s);v.addEventListener('timeupdate',()=>{if(v.duration){r.style.setProperty('--bm-playhead-progress',Math.min(1,v.currentTime/v.duration));if(v.currentTime/v.duration>.9&&session.expert==='running'){session.expert='done';s.textContent='Done · first cut updated'}}});b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();session.expert='running';r.classList.remove('cc-expert-awaiting');r.classList.add('cc-expert-running');s.textContent='Playing · finding highlights + adding B-roll';try{v.currentTime=0}catch{};v.play().catch(()=>{s.textContent='Click the video to continue playback';v.controls=true})})}
function bindMotion(){const r=q('#motion-graphics');if(!r||r.dataset.ccBound)return;r.dataset.ccBound='1';r.classList.add('cc-motion-awaiting');const s=status('Ready · generate these graphics in place');(q('[data-thread-dock="mg"]',r)||q('.agentic-thinking-static',r))?.append(s);r.addEventListener('click',e=>{const a=e.target.closest('a[aria-label="Generate"],a[data-utm-link][href*="target=motion-graphics"]');if(!a||!r.contains(a))return;e.preventDefault();e.stopPropagation();session.motion='done';r.classList.remove('cc-motion-awaiting');r.classList.add('cc-motion-generated');s.textContent='Generated · editable motion graphics ready'},true)}
function bindTranscript(){const r=q('#transcript-captions [data-tc-part="edit"]');if(!r||r.dataset.ccBound)return;r.dataset.ccBound='1';const f=qa('.tc-word[data-tc-filler="true"]',r),b=q('#tc-edit-send',r),s=q('#tc-edit-status',r),m=q('#tc-edit-meta',r),p=q('#tc-edit-prompt',r);if(!f.length||!b)return;f.forEach(x=>x.classList.remove('tc-collapsed'));if(s)s.textContent='Transcript ready';if(m)m.textContent='54 words · 0:43';b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();if(session.transcript!=='raw')return;session.transcript='cleaning';p?.classList.add('tc-prompt-sent');if(s)s.textContent='Removing fillers…';f.forEach((x,i)=>setTimeout(()=>x.classList.add('tc-collapsed'),100+i*85));setTimeout(()=>{session.transcript='clean';if(s)s.textContent='Done — '+f.length+' fillers removed';if(m)m.textContent='46 words · 0:31'},180+f.length*90)},true)}
function bindImage(){const r=q('#image-to-video .itv-story:not(.itv-story-video)');if(!r||r.dataset.ccBound)return;r.dataset.ccBound='1';r.classList.add('cc-image-source');const sh=q('.itv-showcase',r),im=q('.itv-showcase-img',r),b=q('.itv-send-btn,a[aria-label="Generate"]',r);if(!sh||!im||!b)return;const generated=im.currentSrc||im.src;im.dataset.generated=generated;im.src='https://chatcut.io/features/ai-image-generator/cat-white-before.webp';im.alt='Original source before AI generation';const s=status('Source image · result not generated yet');q('.itv-prompt-shell',r)?.append(s);b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();if(session.image==='loading')return;session.image='loading';r.classList.add('cc-image-loading');s.textContent='Generating image…';const o=loading(sh,'Generating image…');setTimeout(()=>{im.src=im.dataset.generated||generated;o.remove();r.classList.remove('cc-image-source','cc-image-loading');r.classList.add('cc-image-generated');session.image='generated';s.textContent='Generated · ready to add to the edit'},850)},true)}
function bindVideo(){const r=q('#image-to-video .itv-story-video');if(!r||r.dataset.ccBound)return;r.dataset.ccBound='1';r.classList.add('cc-video-awaiting');const sh=q('.itv-video-showcase',r),v=q('.itv-showcase-video',r),ref=q('.itv-reference-card img',r),b=q('.itv-send-btn,a[aria-label="Generate"]',r);if(!sh||!v||!ref||!b)return;const ov=document.createElement('img');ov.className='cc-video-reference-overlay';ov.src=ref.currentSrc||ref.src;ov.alt='Selected reference image waiting to become video';sh.append(ov);v.pause();v.addEventListener('play',()=>{if(session.video==='reference')v.pause()});const s=status('Reference image ready · video not generated yet');q('.itv-prompt-shell',r)?.append(s);b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();if(session.video==='loading')return;session.video='loading';s.textContent='Generating video from reference…';const o=loading(sh,'Generating video…');setTimeout(()=>{o.remove();ov.remove();r.classList.remove('cc-video-awaiting');r.classList.add('cc-video-generated');session.video='generated';s.textContent='Generated · original preview video loaded';try{v.currentTime=0}catch{};v.play().catch(()=>v.controls=true)},950)},true)}
function bindMusic(){const r=q('#music-generation');if(!r||r.dataset.ccBound)return;r.dataset.ccBound='1';r.classList.add('cc-music-awaiting');const stack=q('.tc-demo-stack',r),board=q('.tc-music-board',r);if(!stack||!board)return;const row=document.createElement('div');row.className='cc-music-source-row';row.innerHTML='<div class="cc-music-source-video"><video muted loop playsinline preload="metadata" src="https://cdn.chatcut.dev/landing-hero/transcript-captions/project-caption-timeline.mp4"></video><span class="cc-audio-badge">Silent video</span></div><div class="cc-music-prompt-card"><div class="cc-music-prompt-label">Prompt</div><div class="cc-music-prompt-text">Upbeat lo-fi hip hop, relaxed mood, 90 BPM</div><button type="button" class="cc-local-send cc-music-send" aria-label="Generate royalty-free music"><svg viewBox="0 0 24 24"><path d="m5 12 7-7 7 7M12 19V5" fill="none" stroke="currentColor" stroke-width="2.3" stroke-linecap="round" stroke-linejoin="round"/></svg></button><div class="cc-demo-status">Silent source · no music track yet</div></div>';stack.insertBefore(row,board);const v=q('video',row),badge=q('.cc-audio-badge',row),b=q('.cc-music-send',row),s=q('.cc-demo-status',row);v?.play().catch(()=>{});b.addEventListener('click',e=>{e.preventDefault();if(session.music==='loading')return;session.music='loading';r.classList.add('cc-music-loading');s.textContent='Generating royalty-free track…';badge.textContent='Generating music…';setTimeout(()=>{r.classList.remove('cc-music-awaiting','cc-music-loading');r.classList.add('cc-music-generated');session.music='generated';badge.textContent='Music track ready';s.textContent='Generated · waveform + music asset ready'},850)})}
function bindAll(){bindExpert();bindMotion();bindTranscript();bindImage();bindVideo();bindMusic()}
function boot(){bindAll();let queued=false;new MutationObserver(()=>{if(queued)return;queued=true;queueMicrotask(()=>{queued=false;bindAll()})}).observe(document.documentElement,{childList:true,subtree:true});document.addEventListener('astro:page-load',bindAll)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
`;

function absoluteize(html) {
  const attrs = ['href','src','poster','component-url','renderer-url','before-hydration-url'];
  for (const attr of attrs) {
    const re = new RegExp(`(${attr}\\s*=\\s*["'])(/(?!/)[^"']*)(["'])`, 'gi');
    html = html.replace(re, (_m,a,p,z) => `${a}${ORIGIN}${p}${z}`);
  }
  html = html.replace(/url\(\s*(["']?)(\/(?!\/)[^"')]+)\1\s*\)/gi, (_m,q,p)=>`url(${q}${ORIGIN}${p}${q})`);
  html = html.replace(/(&quot;)(\/(?!\/)[^&<>\s]*?)(?=&quot;)/g, (_m,q,p)=>`${q}${ORIGIN}${p}`);
  html = html.replace(/(["'])(\/(?!\/)[A-Za-z0-9._~!$&()*+,;=:@%/?#-]*)(\1)/g, (_m,q,p)=>`${q}${ORIGIN}${p}${q}`);
  return html;
}

function stripTracking(html) {
  return html.replace(/<script\b[^>]*>[\s\S]*?<\/script\s*>/gi, tag => /googletagmanager|google-analytics|posthog|ahrefs|firstpromoter|cloudflareinsights|beacon\.min\.js/i.test(tag) ? '' : tag);
}

async function fetchPage(url) {
  const r = await fetch(url, {redirect:'follow',headers:{'user-agent':'Mozilla/5.0 ChatCutPlayableMirror/1.0','accept':'text/html,application/xhtml+xml'}});
  if (!r.ok) throw new Error(`Fetch failed ${r.status} ${url}`);
  return r.text();
}

await fs.rm(OUT,{recursive:true,force:true});
await fs.mkdir(OUT,{recursive:true});
let html = await fetchPage(`${ORIGIN}/`);
for (const required of ['id="best-moments"','id="transcript-captions"','id="image-to-video"','id="music-generation"']) {
  if (!html.includes(required)) throw new Error(`Production homepage contract changed: missing ${required}`);
}
html = stripTracking(absoluteize(html));
html = html.replace(/<link\s+href="\/"\s+rel="canonical">/i, `<link href="${ORIGIN}/" rel="canonical">`);
html = html.replace(/<\/head\s*>/i, `<style data-cc-playable-patch>${PATCH_CSS}</style></head>`);
html = html.replace(/<\/body\s*>/i, `<script data-cc-playable-patch>${PATCH_JS.replace(/<\/script/gi,'<\\/script')}</script></body>`);
await fs.writeFile(path.join(OUT,'index.html'),html,'utf8');
await fs.writeFile(path.join(OUT,'intent.html'),'<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ChatCut playable intent</title><style>body{font-family:Inter,system-ui;margin:0;background:#fcfbfd;color:#211a13}main{max-width:900px;margin:auto;padding:64px 24px}h1{font-size:clamp(40px,7vw,72px);line-height:.98}p{font-size:20px;line-height:1.55;color:#6b6256}.card{margin-top:28px;padding:24px;border:1px solid #e5e0d8;border-radius:18px;background:#fff}</style><main><h1>Copy first. Edit second.</h1><p>Production ChatCut homepage is fetched at build time. Original layout, CSS, scripts, images and videos stay authoritative. The patch only turns existing demos into local cause→effect interactions.</p><div class="card">Send → original Best Moments clip continues · Transcript → filler words disappear · Generate image/video/music → the original result state appears in place.</div></main>','utf8');
await fs.writeFile(path.join(OUT,'.nojekyll'),'','utf8');
console.log(JSON.stringify({ok:true,bytes:Buffer.byteLength(html),out:OUT},null,2));
